sudo: false
language: node_js
install: true
script: ./test/travis.sh
env:
  matrix:
  - NODE=6
  - NODE=5
  - NODE=4
  - BROWSER=chrome
  - BROWSER=firefox
  - BROWSER=safari
  - BROWSER=android
  - BROWSER=iphone
notifications:
  email: false
